#!/usr/bin/env bash
set -e  # Exit immediately on error


log "Stopping Docker services..."
sudo systemctl stop docker || true
sudo systemctl disable docker || true

log "Removing Docker packages..."
sudo apt-get -y remove --purge docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

log "Removing Docker GPG key and repository..."
sudo rm -f /etc/apt/keyrings/docker.asc
sudo rm -f /etc/apt/sources.list.d/docker.list

log "Removing Docker group..."
sudo groupdel docker || true

log "Removing Docker user from the group..."
sudo deluser $USER docker || true

log "Cleaning up Docker directories..."
sudo rm -rf /var/lib/docker
sudo rm -rf /var/lib/containerd
sudo rm -rf /etc/docker
sudo rm -rf $HOME/.docker

log "Cleaning up unused dependencies..."

log "Docker uninstallation and revert complete!"

