#!/usr/bin/env bash

log() {
    echo "$1"
}

# Remove Neovim installation
if [ -d "$HOME/neovim" ]; then
    log "Removing Neovim source directory..."
    rm -rf "$HOME/neovim"
fi

# Remove Neovim binary if installed
if command -v nvim &> /dev/null; then
    log "Removing Neovim binary..."
    sudo rm -rf /usr/local/bin/nvim
else
    log "Neovim is not installed."
fi

# Remove dependencies installed via APT
log "Removing APT dependencies..."
sudo apt -y remove cmake gettext lua5.1 liblua5.1-0-dev

# Remove Luarocks
if command -v luarocks &> /dev/null; then
    log "Removing Luarocks..."
    sudo rm -rf /usr/local/bin/luarocks
else
    log "Luarocks is not installed."
fi

# Remove downloaded Luarocks source files
if [ -d "$HOME/luarocks-3.11.1" ]; then
    log "Removing Luarocks source directory..."
    rm -rf "$HOME/luarocks-3.11.1"
fi

if [ -f "luarocks-3.11.1.tar.gz" ]; then
    log "Removing Luarocks tarball..."
    rm luarocks-3.11.1.tar.gz
fi

log "Uninstallation of Neovim and Luarocks complete!"

