#!/usr/bin/env bash

pkgs=(
    git 
)

snaps=(
    alacritty
    goland
    datagrip
    firefox
)

(
    for p in ${pkgs[@]}
    do
        sudo apt -y remove $p
    done
)

(
    for s in ${snaps[@]}

    do
        sudo snap remove $s
    done
)
