#!/usr/bin/env bash

log() {
    echo "[zsh:uninstall] $1"
}

# Reset default shell to Bash
if [[ "$SHELL" == *"zsh" ]]; then
    log "Resetting shell to Bash..."
    sudo chsh -s "$(which bash)" "$USER"
fi

# Remove Oh My Zsh
if [[ -d "$HOME/.oh-my-zsh" ]]; then
    log "Removing Oh My Zsh..."
    rm -rf "$HOME/.oh-my-zsh"
fi

# Remove Zsh config files
log "Removing Zsh configuration files..."
rm -f "$HOME/.zshrc" "$HOME/.zsh_history"

# Uninstall Zsh
log "Uninstalling..."
sudo apt -y remove zsh

log "Uninstallation completed!"
