#!/usr/bin/env bash

sudo apt update
sudo apt install -y zsh
hash -r

sudo chsh -s $(which zsh)

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
	echo "Oh My Zsh already installed, skipping."
fi

