[env]
TERM = "alacritty"

[terminal]
shell = { program = "/usr/bin/tmux" }

[window]
startup_mode = "Fullscreen"

[scrolling]
history = 300
multiplier = 3

[keyboard]
bindings = [
	{ key = "V", mods = "Control|Shift", action = "Paste" },
	{ key = "C", mods = "Control|Shift", action = "Copy" }
]

